### PR TITLE
travis: update go version

### PR DESCRIPTION
**Pull request by dvrkps**

### CODE REVIEW

**Comment by dvrkps** [comment]
1.x match latest stable version. No special reason, only gardening.

**Comment by shlomi-noach** [comment]
> 1.x match latest stable version. No special reason, only gardening.

However it will match `1.4` if for some reason that _is_ the latest release for travis or another tool ; is that not a concern?

**Comment by dvrkps** [comment]
I'm not sure.

Maybe you can guard this by setting:

go:
- 1.5.x
- 1.6.x
- 1.7.x
- 1.8.x
- 1.9.x

instead 1.x

**Comment by dvrkps** [comment]
@shlomi-noach ping 😃

**Comment by shlomi-noach** [comment]
@dvrkps: reimplemented in https://github.com/github/ccql/pull/47

**Pull request closed without merging**
